import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const BOARD_JSON = path.join(ROOT, 'docs', 'board.json');
const BOARD_MD = path.join(ROOT, 'docs', 'board.md');

function readBoard() {
  const raw = fs.readFileSync(BOARD_JSON, 'utf8');
  return JSON.parse(raw);
}

function writeBoard(board) {
  board.meta.updatedAt = new Date().toISOString();
  fs.writeFileSync(BOARD_JSON, `${JSON.stringify(board, null, 2)}\n`, 'utf8');
}

function parseArgs(argv) {
  const result = {};
  for (let i = 0; i < argv.length; i += 1) {
    const token = argv[i];
    if (!token.startsWith('--')) {
      continue;
    }
    const key = token.slice(2);
    const value = argv[i + 1] && !argv[i + 1].startsWith('--') ? argv[++i] : 'true';
    result[key] = value;
  }
  return result;
}

function nextId(items) {
  const nums = items
    .map((x) => x.id)
    .filter((x) => /^WC-\d+$/.test(x))
    .map((x) => Number(x.split('-')[1]));

  const max = nums.length ? Math.max(...nums) : 0;
  return `WC-${String(max + 1).padStart(3, '0')}`;
}

function renderBoardMd(board) {
  const lines = [];
  lines.push('# Local Board');
  lines.push('');
  lines.push('This file is generated from docs/board.json.');
  lines.push('Do not edit this file manually.');
  lines.push('');
  lines.push(`Last updated: ${board.meta.updatedAt}`);
  lines.push('');

  for (const column of board.columns) {
    lines.push(`## ${column.title}`);
    lines.push('');

    const items = board.items.filter((x) => x.status === column.id);
    if (items.length === 0) {
      lines.push('- _(empty)_');
      lines.push('');
      continue;
    }

    for (const item of items) {
      const tags = item.tags?.length ? item.tags.map((t) => `#${t}`).join(' ') : '';
      const refs = item.specRefs?.length ? item.specRefs.join(', ') : '';
      lines.push(`- **${item.id}** [${item.priority}] ${item.title}`);
      lines.push(`  - owner: ${item.owner || 'unassigned'}`);
      lines.push(`  - tags: ${tags || 'none'}`);
      lines.push(`  - spec refs: ${refs || 'none'}`);
      lines.push(`  - notes: ${item.notes || 'none'}`);
    }

    lines.push('');
  }

  fs.writeFileSync(BOARD_MD, `${lines.join('\n')}\n`, 'utf8');
}

function ensureStatus(board, status) {
  const ok = board.columns.some((x) => x.id === status);
  if (!ok) {
    throw new Error(`Unknown status '${status}'. Valid statuses: ${board.columns.map((x) => x.id).join(', ')}`);
  }
}

function addItem(args) {
  if (!args.title) {
    throw new Error('add requires --title');
  }

  const board = readBoard();
  const status = args.status || 'backlog';
  ensureStatus(board, status);

  const item = {
    id: nextId(board.items),
    title: args.title,
    status,
    priority: args.priority || 'P2',
    owner: args.owner || '',
    tags: args.tags ? args.tags.split(',').map((x) => x.trim()).filter(Boolean) : [],
    specRefs: args.refs ? args.refs.split(',').map((x) => x.trim()).filter(Boolean) : [],
    notes: args.notes || '',
    updatedAt: new Date().toISOString()
  };

  board.items.push(item);
  writeBoard(board);
  renderBoardMd(board);
  console.log(`Added ${item.id}`);
}

function moveItem(args) {
  if (!args.id || !args.status) {
    throw new Error('move requires --id and --status');
  }

  const board = readBoard();
  ensureStatus(board, args.status);

  const item = board.items.find((x) => x.id === args.id);
  if (!item) {
    throw new Error(`Item '${args.id}' not found`);
  }

  item.status = args.status;
  item.updatedAt = new Date().toISOString();

  writeBoard(board);
  renderBoardMd(board);
  console.log(`Moved ${args.id} -> ${args.status}`);
}

function noteItem(args) {
  if (!args.id || !args.note) {
    throw new Error('note requires --id and --note');
  }

  const board = readBoard();
  const item = board.items.find((x) => x.id === args.id);
  if (!item) {
    throw new Error(`Item '${args.id}' not found`);
  }

  item.notes = args.note;
  item.updatedAt = new Date().toISOString();

  writeBoard(board);
  renderBoardMd(board);
  console.log(`Updated note for ${args.id}`);
}

function setOwner(args) {
  if (!args.id || !args.owner) {
    throw new Error('owner requires --id and --owner');
  }

  const board = readBoard();
  const item = board.items.find((x) => x.id === args.id);
  if (!item) {
    throw new Error(`Item '${args.id}' not found`);
  }

  item.owner = args.owner;
  item.updatedAt = new Date().toISOString();

  writeBoard(board);
  renderBoardMd(board);
  console.log(`Updated owner for ${args.id}`);
}

function doneItem(args) {
  moveItem({ ...args, status: 'done' });
}

function renderOnly() {
  const board = readBoard();
  renderBoardMd(board);
  console.log('Rendered docs/board.md from docs/board.json');
}

function usage() {
  console.log(`Board CLI\n\nCommands:\n  render\n  add --title "..." [--status backlog|in-progress|blocked|done] [--priority P1|P2|P3] [--owner name] [--tags a,b] [--refs file1,file2] [--notes text]\n  move --id WC-001 --status in-progress\n  note --id WC-001 --note "..."\n  owner --id WC-001 --owner "name"\n  done --id WC-001\n`);
}

function main() {
  const [, , command, ...rest] = process.argv;
  const args = parseArgs(rest);

  try {
    switch (command) {
      case 'render':
        renderOnly();
        break;
      case 'add':
        addItem(args);
        break;
      case 'move':
        moveItem(args);
        break;
      case 'note':
        noteItem(args);
        break;
      case 'owner':
        setOwner(args);
        break;
      case 'done':
        doneItem(args);
        break;
      default:
        usage();
        process.exitCode = 1;
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.error(`Error: ${message}`);
    process.exitCode = 1;
  }
}

main();
