import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const BOARD_JSON = path.join(ROOT, 'docs', 'board.json');
const BOARD_MD = path.join(ROOT, 'docs', 'board.md');

function readJsonBoard() {
  const raw = fs.readFileSync(BOARD_JSON, 'utf8');
  return JSON.parse(raw);
}

function renderBoardMarkdown(board) {
  const lines = [];
  lines.push('# Local Board');
  lines.push('');
  lines.push('This file is generated from docs/board.json.');
  lines.push('Do not edit this file manually.');
  lines.push('');
  lines.push(`Last updated: ${board.meta.updatedAt}`);
  lines.push('');

  for (const column of board.columns) {
    lines.push(`## ${column.title}`);
    lines.push('');

    const items = board.items.filter((x) => x.status === column.id);
    if (items.length === 0) {
      lines.push('- _(empty)_');
      lines.push('');
      continue;
    }

    for (const item of items) {
      const tags = item.tags?.length ? item.tags.map((t) => `#${t}`).join(' ') : '';
      const refs = item.specRefs?.length ? item.specRefs.join(', ') : '';
      lines.push(`- **${item.id}** [${item.priority}] ${item.title}`);
      lines.push(`  - owner: ${item.owner || 'unassigned'}`);
      lines.push(`  - tags: ${tags || 'none'}`);
      lines.push(`  - spec refs: ${refs || 'none'}`);
      lines.push(`  - notes: ${item.notes || 'none'}`);
    }

    lines.push('');
  }

  return `${lines.join('\n')}\n`;
}

function validateBoardShape(board) {
  if (!board.meta || !board.meta.project || !board.meta.updatedAt) {
    throw new Error('board.meta.project and board.meta.updatedAt are required.');
  }

  if (!Array.isArray(board.columns) || board.columns.length === 0) {
    throw new Error('board.columns must be a non-empty array.');
  }

  if (!Array.isArray(board.items)) {
    throw new Error('board.items must be an array.');
  }

  const statusSet = new Set(board.columns.map((x) => x.id));
  const idSet = new Set();

  for (const item of board.items) {
    if (!item.id || !item.title || !item.status) {
      throw new Error('each item requires id, title, status');
    }

    if (idSet.has(item.id)) {
      throw new Error(`duplicate item id: ${item.id}`);
    }
    idSet.add(item.id);

    if (!statusSet.has(item.status)) {
      throw new Error(`item ${item.id} has unknown status '${item.status}'`);
    }
  }
}

function main() {
  const board = readJsonBoard();
  validateBoardShape(board);

  const expected = renderBoardMarkdown(board);
  const actual = fs.readFileSync(BOARD_MD, 'utf8');

  if (expected !== actual) {
    console.error('Board mismatch: docs/board.md is out of sync with docs/board.json');
    console.error('Run: npm run board:render');
    process.exitCode = 1;
    return;
  }

  console.log('Board check passed. docs/board.md matches docs/board.json');
}

main();
